
virtuosodata:
  #  build: virtuosodata-fromrdf
  build: virtuosodata-frombackup
      
virtuoso:
  image: stain/virtuoso
  ports:
    - "8895:8890"
  volumes_from:
    - virtuosodata
    # TODO: /staging
  #restart: always
  
mysqldata:
  image: busybox
  volumes:
    - /var/lib/mysql

mysql:    
  image: mysql
  volumes_from:
    - mysqldata
  environment:
    - MYSQL_ROOT_PASSWORD=uCie0ahgah
    - MYSQL_DATABASE=ims
    - MYSQL_USER=ims
    - MYSQL_PASSWORD=ims
  #restart: always

mysqlstaging:
  build: mysqlstaging
  links:
    - mysql

ims:
  image: openphacts/identitymappingservice
  ports:
    - "8182:8080"
  links:
    - mysql
    - mysqlstaging
  #restart: always

memcached:
  image: memcached
    
api:
  image: openphacts/ops-linkeddataapi
  ports:
    - "8181:80"
  links:
    - ims
    - memcached
    - virtuoso:sparql
  #restart: always
    
explorer2:
  image: openphacts/explorer2
  ports:
    - "3000:3000"
  links:
    - api
  environment:
    - API_URL http://api/
  #restart: always


#elasticsearch:
#  image: elasticsearch
##  TODO: Data loading
#ops-search:
# image: openphacts/ops-search
