ld_dir('/media/SSD/current_data/' , 'cw_url_preflabels_20120620_validTurtle.ttl' , 'http://www.conceptwiki.org' );
ld_dir('/media/SSD/current_data/' , 'CW_ChemSpider.ttl' , 'http://www.conceptwiki.org' );
ld_dir('/media/SSD/current_data/' , 'inference.ttl' , 'http://purl.uniprot.org/enzyme/inference' );
ld_dir('/media/SSD/current_data/' , 'direct.ttl' , 'http://purl.uniprot.org/enzyme/direct' );
ld_dir('/media/SSD/current_data/' , 'enzyme_names_comments.ttl' , 'http://purl.uniprot.org/enzyme' );
ld_dir('/media/SSD/current_data/' , 'drugbank_dump.nt' , 'http://linkedlifedata.com/resource/drugbank' );
ld_dir('/media/SSD/current_data/' , 'drug_type_labels.ttl' , 'http://linkedlifedata.com/resource/drugbank' );
ld_dir('/media/SSD/current_data/' , 'drug_category_labels.ttl' , 'http://linkedlifedata.com/resource/drugbank' );
--ld_dir('/media/SSD/current_data/' , 'activities.nt' , 'http://data.kasabi.com/dataset/chembl-rdf' );
--ld_dir('/media/SSD/current_data/' , 'activities_qudt.nt' , 'http://data.kasabi.com/dataset/chembl-rdf' );
--ld_dir('/media/SSD/current_data/' , 'assays.nt' , 'http://data.kasabi.com/dataset/chembl-rdf' );
--ld_dir('/media/SSD/current_data/' , 'compounds.nt' , 'http://data.kasabi.com/dataset/chembl-rdf' );
--ld_dir('/media/SSD/current_data/' , 'docs.nt' , 'http://data.kasabi.com/dataset/chembl-rdf' );
--ld_dir('/media/SSD/current_data/' , 'targets.nt' , 'http://data.kasabi.com/dataset/chembl-rdf' );
--ld_dir('/media/SSD/current_data/' , 'chemspider_match.nt' , 'http://data.kasabi.com/dataset/chembl-rdf' );
--ld_dir('/media/SSD/current_data/' , 'compounds_props.nt' , 'http://data.kasabi.com/dataset/chembl-rdf' );
--ld_dir('/media/SSD/current_data/' , 'compounds_chebi.nt' , 'http://data.kasabi.com/dataset/chembl-rdf' );
--ld_dir('/media/SSD/current_data/' , 'act_qudt_act.nt' , 'http://data.kasabi.com/dataset/chembl-rdf' );
--ld_dir('/media/SSD/current_data/' , 'act_qudt_ic50.nt' , 'http://data.kasabi.com/dataset/chembl-rdf' );
--ld_dir('/media/SSD/current_data/' , 'act_qudt_inhib.nt' , 'http://data.kasabi.com/dataset/chembl-rdf' );
--ld_dir('/media/SSD/current_data/' , 'act_qudt_pot.nt' , 'http://data.kasabi.com/dataset/chembl-rdf' );
--ld_dir('/media/SSD/current_data/' , 'act_qudt_types.nt' , 'http://data.kasabi.com/dataset/chembl-rdf' );
ld_dir('/media/SSD/current_data/' , 'swissprot_24052013.rdf.xml' , 'http://purl.uniprot.org' );
ld_dir('/media/SSD/current_data/' , 'uniparc_24052013.rdf.xml' , 'http://purl.uniprot.org' );
ld_dir('/media/SSD/current_data/' , 'uniref_24052013.rdf.xml' , 'http://purl.uniprot.org' );
ld_dir('/media/SSD/current_data/' , 'chebi_direct.nt' , 'http://www.ebi.ac.uk/chebi/direct' );
ld_dir('/media/SSD/current_data/' , 'chebi_inference.ttl' , 'http://www.ebi.ac.uk/chebi/inference' );
ld_dir('/media/SSD/current_data/' , 'chebi_class_labels.nt' , 'http://www.ebi.ac.uk/chebi' );
ld_dir('/media/SSD/current_data/' , 'PROPERTIES_ChEMBL20120731.ttl' , 'http://www.chemspider.com' );
ld_dir('/media/SSD/current_data/' , 'SYNONYMS_ChEMBL20120731.ttl' , 'http://www.chemspider.com' );
ld_dir('/media/SSD/current_data/linksets_dev' , 'LINKSET_EXACT_DRUGBANK20130408.ttl' , 'http://www.chemspider.com' );
ld_dir('/media/SSD/current_data/linksets_dev' , 'LINKSET_EXACT_CHEBI20130408.ttl' , 'http://www.chemspider.com' );
ld_dir('/media/SSD/current_data/linksets_dev/' , 'LINKSET_EXACT_CHEMBL20130408.ttl' , 'http://www.chemspider.com' );
ld_dir('/media/SSD/current_data/' , 'PROPERTIES_DrugBank20120731.ttl' , 'http://www.chemspider.com' );
ld_dir('/media/SSD/current_data/' , 'PROPERTIES_MeSH20120731.ttl' , 'http://www.chemspider.com' );
ld_dir('/media/SSD/current_data/' , 'PROPERTIES_ChEBI20120731.ttl' , 'http://www.chemspider.com' );
ld_dir('/media/SSD/current_data/' , 'PROPERTIES_PDB20120731.ttl' , 'http://www.chemspider.com' );
ld_dir('/media/SSD/current_data/' , 'SYNONYMS_MeSH20120731.ttl' , 'http://www.chemspider.com' );
ld_dir('/media/SSD/current_data/' , 'SYNONYMS_ChEBI20120731.ttl' , 'http://www.chemspider.com' );
ld_dir('/media/SSD/current_data/' , 'SYNONYMS_PDB20120731.ttl' , 'http://www.chemspider.com' );
ld_dir('/media/SSD/current_data/' , 'wpContent_v0.0.69675_20130710.ttl' , 'http://www.wikipathways.org' );
--ld_dir('/media/SSD/current_data/pubmed_subset_rdf_doc/pubmed_subset' , '*.n3' , 'http://www.ubo.textmining.org' );
--ld_dir('/media/SSD/current_data/pubmed_subset_rdf_DrugBank_V1/pubmed_subset' , '*.n3' , 'http://www.ubo.textmining.org' );
--ld_dir('/media/SSD/current_data/pubmed_subset_rdf_Genes_HomoSapiens_V1/pubmed_subset' , '*.n3' , 'http://www.ubo.textmining.org' );
--ld_dir('/media/SSD/current_data/pubmed_subset_rdf_MeSHDisease_V1/pubmed_subset' , '*.n3' , 'http://www.ubo.textmining.org' );
--ld_dir('/media/SSD/current_data/pubmed_subset_rdf_peregrine/pubmed_subset' , '*.n3' , 'http://www.ubo.textmining.org' );
--ld_dir('/media/SSD/current_data/pubmed_subset_rdf_peregrine_dict' , '*.n3' , 'http://www.ubo.textmining.org' );
--ld_dir('/media/SSD/current_data/pubmed_subset_rdf_pm_dict' , '*.n3' , 'http://www.ubo.textmining.org' );
--ld_dir('/media/SSD/current_data/pubmed_subset_rdf_Taxonomy_NCBI_V1/pubmed_subset' , '*.n3' , 'http://www.ubo.textmining.org' );
ld_dir('/media/SSD/current_data/api-config-files' , '*.ttl' , 'http://www.openphacts.org/api' );
ld_dir('/media/SSD/current_data/' , 'go_daily-termdb.owl' , 'http://www.geneontology.org' );
ld_dir('/media/SSD/current_data/' , 'go_daily-termdb.nt' , 'http://www.geneontology.org/terms' );
ld_dir('/media/SSD/current_data/GOA' , '*.rdf' , 'http://www.openphacts.org/goa' );
ld_dir('/media/SSD/current_data/void' , '*.ttl' , 'http://www.openphacts.org/api/datasetDescriptors' );
ld_dir('/media/SSD/current_data/' , 'gvk_data.nt', 'http://www.openphacts.org/gvk' );
ld_dir('/media/SSD/current_data/' , 'tr_data.nt', 'http://www.openphacts.org/tr' );
ld_dir('/media/SSD/current_data/' , 'faers-of-2012-generated-on-2012-07-09.nt', 'http://aers.data2semantics.org/');
ld_dir('/media/SSD/current_data/chembl16', '*.ttl', 'http://www.ebi.ac.uk/chembl');
ld_dir('/media/SSD/current_data/' , 'ops_units.nt', 'http://www.openphacts.org/units');
ld_dir('/media/SSD/current_data/' , 'unit_labels.nt', 'http://www.openphacts.org/units');
ld_dir('/media/SSD/current_data/target_tree' , 'targetTreeDirect.ttl', 'http://www.ebi.ac.uk/chembl/target/direct');
ld_dir('/media/SSD/current_data/target_tree' , 'targetTreeInference.ttl', 'http://www.ebi.ac.uk/chembl/target/inference');
